### ISSUE TITLE
cannot import name 'iterate' from 'gym.vector.utils'

### ISSUE THREAD

**Issue by MyIDis12138** [Farama-Foundation/SuperSuit#166]
when I tried to import supersuit, bugs followed with "cannot import name 'iterate' from 'gym.vector.utils' " 
 output is:
Traceback (most recent call last):
  File "/home/mmo/Desktop/zoo_learning/zoo.py", line 4, in <module>
    import supersuit as ss
  File "/home/mmo/miniconda3/envs/zoo/lib/python3.9/site-packages/supersuit/__init__.py", line 29, in <module>
    from .vector.vector_constructors import (
  File "/home/mmo/miniconda3/envs/zoo/lib/python3.9/site-packages/supersuit/vector/__init__.py", line 2, in <module>
    from .multiproc_vec import ProcConcatVec  # NOQA
  File "/home/mmo/miniconda3/envs/zoo/lib/python3.9/site-packages/supersuit/vector/multiproc_vec.py", line 8, in <module>
    from gym.vector.utils import (
ImportError: cannot import name 'iterate' from 'gym.vector.utils' (/home/mmo/miniconda3/envs/zoo/lib/python3.9/site-packages/gym/vector/utils/__init__.py)

**Comment by benblack769** [comment]
I think this is a version mismatch between supersuit and gym. The latest version of supersuit requires `gym>=0.22.0`.

**Comment by MyIDis12138** [comment]
Thanks benblack769, the reason has been found that stable_baselines3 automatically downgrade my gym version.
